export const SET_POKEMONS = 'SET_POKEMONS';
export type SET_POKEMONS = typeof SET_POKEMONS;

export const UPDATE_POKEMONS = 'UPDATE_POKEMONS';
export type UPDATE_POKEMONS = typeof UPDATE_POKEMONS;

export const SET_POKEMON_INFO = 'SET_POKEMON_INFO';
export type SET_POKEMON_INFO = typeof SET_POKEMON_INFO;

export const SET_ALL_TYPES = 'SET_ALL_TYPES';
export type SET_ALL_TYPES = typeof SET_ALL_TYPES;

export const SET_SELECTED_TYPE = 'SET_SELECTED_TYPE';
export type SET_SELECTED_TYPE = typeof SET_SELECTED_TYPE;

export const SET_PICKER_ITEMS = 'SET_PICKER_ITEMS';
export type SET_PICKER_ITEMS = typeof SET_PICKER_ITEMS;

export const SEARCH_POKEMON = 'SEARCH_POKEMON';
export type SEARCH_POKEMON = typeof SEARCH_POKEMON;

export const GO_TO_POKEMON = 'GO_TO_POKEMON';
export type GO_TO_POKEMON = typeof GO_TO_POKEMON;
