export const SET_POKEMONS = 'SET_POKEMONS';
export type SET_POKEMONS = typeof SET_POKEMONS;

export const UPDATE_POKEMONS = 'UPDATE_POKEMONS';
export type UPDATE_POKEMONS = typeof UPDATE_POKEMONS;

export const SET_POKEMON_INFO = 'SET_POKEMON_INFO';
export type SET_POKEMON_INFO = typeof SET_POKEMON_INFO;
